// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twrbtaqugutkbkhizgxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3cmJ0YXF1Z3V0a2JraGl6Z3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1ODA5ODAsImV4cCI6MjA5MzE1Njk4MH0.8vRa7SQ3hVLS7_miqswzv01Z3Dx_3lWaNPopYCZ5XX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});